### PR TITLE
Optionally skip linting whitespace-only lines.

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Follow up on #1, have not tested this.

Does `lintWSLines` sound like a good option name?

Should the relinting happen on change of this option (I copied the code from the main options to this, since it seems like that makes sense.).

### CODE REVIEW

**Comment by markmcintyre** [comment]
Perhaps let's call it "skipBlankLines" for the sake of user readability, with a default of `false`. Otherwise this looks good!

**Comment by Mark-Simulacrum** [comment]
@markmcintyre Should be good now.

**Comment by Mark-Simulacrum** [comment]
Corrected the `if` statement.. I agree that the `!` is probably countering the option name there.

**Comment by markmcintyre** [comment]
Works great! Thanks, @Mark-Simulacrum.

**Comment by TomMalbran** [comment]
Nice Job. Thanks!!

**Pull request merged**
